# Generated by Django 4.2.2 on 2023-06-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_id', models.IntegerField()),
                ('definition_id', models.IntegerField()),
                ('scans', models.IntegerField()),
                ('url', models.URLField()),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
            ],
        ),
    ]
